services:
  db:
    image: postgres:15-alpine
    container_name: liquiverde_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: liquiverde
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: liquiverde_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://admin:admin123@db:5432/liquiverde
    volumes:
      - ./backend:/app
  
  frontend:
    build: ./frontend
    container_name: liquiverde_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data: